In [2]:
import pandas as pd
import datetime as dt
import csv

In [19]:
df_photo = pd.read_csv('./db/photo.csv', index_col=0)
df_photo.head(3)

               filename                        imagepath   aID
photoID
0        com_kite_001sm  evimg2/a1-10/COM_KITE_001SM.jpg  32.0
1        com_kite_002sm  evimg2/a1-10/COM_KITE_002SM.jpg  32.0
2        com_kite_003sm  evimg2/a1-10/COM_KITE_003SM.jpg  32.0

keywords,year,_material,_height,_width,_time,_description,id

In [20]:
df_album = pd.read_csv('./db/album.csv', index_col=0)
df_album.dropna(inplace=True)
df_album['aDate'] = df_album['aDate'].map(lambda x: dt.datetime.strptime(x, '%Y-%m-%d %H:%M:%S').strftime('%Y-%m'))
df_album.head(3)

,albumID,name,aTitle,aDate,mDate,aURL
0,0,lib-0006,OCLC Institute Knowledge Management: Methods a...,2012-03,2012-03-08 04:05:01,http://digitalimages.ust.hk/gallery/?p=601
1,1,lib-0011,"Recent Works by Karla Gaenessler, 8 November 2...",2012-03,2012-03-08 04:05:03,http://digitalimages.ust.hk/gallery/?p=602
2,2,lib-0101,2001 PNC Pacific Neighborhood Consortium Annua...,2012-03,2012-03-08 04:05:03,http://digitalimages.ust.hk/gallery/?p=603

In [21]:
df = df_photo.loc[:, ['filename', 'aID', 'imagepath']]
df['pid'] = df.index
for i in df.index:
    temp = df_album[df_album['albumID'] == df.loc[i, 'aID']]
    if not temp.empty:
        df.loc[i, '_aID'] = temp['aTitle'].values
        df.loc[i, 'year'] = temp['aDate'].values
        df.loc[i, '_URL'] = temp['aURL'].values
df.dropna(inplace=True)
df.rename({'filename':'_name', 'imagepath':'id'},axis=1, inplace=True)
df['keyword'] = ''
df.to_csv('./db/data.csv', index=False)
df

,_name,aID,id,pid,_aID,year,_URL,keyword
photoID,,,,,,,,
0,com_kite_001sm,32.0,evimg2/a1-10/COM_KITE_001SM.jpg,0,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery2/?p=639,
1,com_kite_002sm,32.0,evimg2/a1-10/COM_KITE_002SM.jpg,1,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery2/?p=639,
2,com_kite_003sm,32.0,evimg2/a1-10/COM_KITE_003SM.jpg,2,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery2/?p=639,
3,com_kite_004sm,32.0,evimg2/a1-10/COM_KITE_004SM.jpg,3,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery2/?p=639,
4,com_kite_005sm,32.0,evimg2/a1-10/COM_KITE_005SM.jpg,4,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery2/?p=639,
...,...,...,...,...,...,...,...,...
32987,2-2_057_02-2,982.0,evimg2/fm-vpaao-9912/2-2_057_02.jpg,32987,Visit of Dan Tsui to UST,2015-04,http://digitalimages.ust.hk/gallery/?p=1892,
32988,2-2_057_03-2,982.0,evimg2/fm-vpaao-9912/2-2_057_03.jpg,32988,Visit of Dan Tsui to UST,2015-04,http://digitalimages.ust.hk/gallery/?p=1892,
32989,2-2_057_04-2,982.0,evimg2/fm-vpaao-9912/2-2_057_04.jpg,32989,Visit of Dan Tsui to UST,2015-04,http://digitalimages.ust.hk/gallery/?p=1892,
32990,2-2_057_05-2,982.0,evimg2/fm-vpaao-9912/2-2_057_05.jpg,32990,Visit of Dan Tsui to UST,2015-04,http://digitalimages.ust.hk/gallery/?p=1892,
32991,2-2_057_06-2,982.0,evimg2/fm-vpaao-9912/2-2_057_06.jpg,32991,Visit of Dan Tsui to UST,2015-04,http://digitalimages.ust.hk/gallery/?p=1892,

In [99]:
df['keyword'] = ""
df.to_csv('./db/data.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)

In [105]:
df['year'].unique()

array([2012., 2014., 2015.])

In [9]:
df = pd.read_csv('./data/data.csv')
df['id2'] = df['id'].map(lambda x: x[: -len(x.split('/')[2]) ] +'thumbs/thumbs_'+x.split('/')[2])
df.head(5)

,_name,aID,id,pid,_description,year,_URL,keyword,id2
0,com_kite_001sm,32,evimg2/a1-10/COM_KITE_001SM.jpg,0,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"megaphone,catch,trumpet,crowd,person,instrumen...",evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg
1,com_kite_002sm,32,evimg2/a1-10/COM_KITE_002SM.jpg,1,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"chair,crowd,event,foldingchair,collect,gatheri...",evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg
2,com_kite_003sm,32,evimg2/a1-10/COM_KITE_003SM.jpg,2,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"catch,couple,field,gathering,grass,grassy,gree...",evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg
3,com_kite_004sm,32,evimg2/a1-10/COM_KITE_004SM.jpg,3,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"fence,grass,person,sign,stand,woman",evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg
4,com_kite_005sm,32,evimg2/a1-10/COM_KITE_005SM.jpg,4,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"building,child,cloudy,field,fly,girl,grass,gra...",evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg

In [10]:
df.to_csv('./data/data.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)

In [8]:
df = pd.read_csv('data/data.csv', index_col=None)
df.loc[:,"id3"] = df.loc[:, 'id']
df['id'] = df['id'].map(lambda x: x.split('/')[3][7:].split('.')[0])
df.head()

,_name,aID,id2,pid,_description,year,_URL,keywords,id,id3
0,com_kite_001sm,32,evimg2/a1-10/COM_KITE_001SM.jpg,0,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"megaphone,catch,trumpet,crowd,person,instrumen...",COM_KITE_001SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg
1,com_kite_002sm,32,evimg2/a1-10/COM_KITE_002SM.jpg,1,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"chair,crowd,event,foldingchair,collect,gatheri...",COM_KITE_002SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg
2,com_kite_003sm,32,evimg2/a1-10/COM_KITE_003SM.jpg,2,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"catch,couple,field,gathering,grass,grassy,gree...",COM_KITE_003SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg
3,com_kite_004sm,32,evimg2/a1-10/COM_KITE_004SM.jpg,3,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"fence,grass,person,sign,stand,woman",COM_KITE_004SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg
4,com_kite_005sm,32,evimg2/a1-10/COM_KITE_005SM.jpg,4,Kite Flying Contest,2012,http://digitalimages.ust.hk/gallery2/?p=639,"building,child,cloudy,field,fly,girl,grass,gra...",COM_KITE_005SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg

In [25]:
df1.to_csv('./data/data.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)

In [23]:
df1 = pd.read_csv('data/data.csv', index_col=None)
df2 = pd.read_csv('db/data.csv', index_col=None)
df1['year'] = df2['year']
df1.head()

,_name,aID,id2,pid,_description,year,_URL,keywords,id,id3,_id3
0,com_kite_001sm,32,evimg2/a1-10/COM_KITE_001SM.jpg,0,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery/p=639,"megaphone,catch,trumpet,crowd,person,instrumen...",COM_KITE_001SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg
1,com_kite_002sm,32,evimg2/a1-10/COM_KITE_002SM.jpg,1,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery/p=639,"chair,crowd,event,foldingchair,collect,gatheri...",COM_KITE_002SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg
2,com_kite_003sm,32,evimg2/a1-10/COM_KITE_003SM.jpg,2,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery/p=639,"catch,couple,field,gathering,grass,grassy,gree...",COM_KITE_003SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg
3,com_kite_004sm,32,evimg2/a1-10/COM_KITE_004SM.jpg,3,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery/p=639,"fence,grass,person,sign,stand,woman",COM_KITE_004SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg
4,com_kite_005sm,32,evimg2/a1-10/COM_KITE_005SM.jpg,4,Kite Flying Contest,2012-08,http://digitalimages.ust.hk/gallery/p=639,"building,child,cloudy,field,fly,girl,grass,gra...",COM_KITE_005SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg

In [25]:
def temp(x):
    if x == 'Date unknown':
        return x
    elif type(x) == str:
        try:
            result = dt.datetime.strptime(x, '%Y-%m-%d %H:%M:%S').strftime('%Y-%m')
            return result
        except:
            return x
    elif type(x) == dt.datetime:
        try:
            result = x.strftime('%Y-%m')
            return result
        except:
            return x
    else:
        return "Date unknown"

df1 = pd.read_csv('data/data.csv', index_col=None)
df2 = pd.read_excel('db/album_wEventDate.xlsx', index_col=0)
df2['evdate'] = df2['evdate'].map(lambda x : temp(x))
# df2['evdate'] = df2['evdate'].map(lambda x: x.strftime('%Y-%m'))
df2.head()

,albumID,name,aTitle,aDate,mDate,aURL,evdate,dept,evtype
0,0,lib-0006,OCLC Institute Knowledge Management: Methods a...,2012-03-08 04:05:01,2012-03-08 04:05:01,http://digitalimages.ust.hk/gallery/?p=601,2000-06,Library,Colloquium
1,1,lib-0011,"Recent Works by Karla Gaenessler, 8 November 2...",2012-03-08 04:05:03,2012-03-08 04:05:03,http://digitalimages.ust.hk/gallery/?p=602,2000-11,Library,Exhibition
2,2,lib-0101,2001 PNC Pacific Neighborhood Consortium Annua...,2012-03-08 04:05:03,2012-03-08 04:05:03,http://digitalimages.ust.hk/gallery/?p=603,2001-01,Library,Conference
3,3,lib-0102,"Calligraphy Works by Grace. Y.T. Tong, 13 Febr...",2012-03-08 04:05:03,2012-03-08 04:05:03,http://digitalimages.ust.hk/gallery/?p=604,2001-02,Library,Exhibition
4,4,lib-0109,&quot;Landmarks in Science and Technology&quot...,2012-03-08 04:05:04,2012-03-08 04:05:04,http://digitalimages.ust.hk/gallery/?p=605,2001-09,Library,Exhibition

In [35]:
df2.columns

Index(['albumID', 'name', 'aTitle', 'aDate', 'mDate', 'aURL', 'evdate', 'dept',
       'evtype'],
      dtype='object')

In [45]:
for i in range(len(df1)):
    temp = df2[df2['albumID'] == df1.loc[i, 'aID']]['evdate']
    if temp.any():
        if temp.values[0] != 'Date unknown':
            df1.loc[i, 'year'] = temp.values[0]
df1.head()

,_name,aID,id2,pid,_description,year,_URL,keywords,id,id3,_id3
0,com_kite_001sm,32,evimg2/a1-10/COM_KITE_001SM.jpg,0,Kite Flying Contest,1995-06,http://digitalimages.ust.hk/gallery/p=639,"megaphone,catch,trumpet,crowd,person,instrumen...",COM_KITE_001SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_001SM.jpg
1,com_kite_002sm,32,evimg2/a1-10/COM_KITE_002SM.jpg,1,Kite Flying Contest,1995-06,http://digitalimages.ust.hk/gallery/p=639,"chair,crowd,event,foldingchair,collect,gatheri...",COM_KITE_002SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_002SM.jpg
2,com_kite_003sm,32,evimg2/a1-10/COM_KITE_003SM.jpg,2,Kite Flying Contest,1995-06,http://digitalimages.ust.hk/gallery/p=639,"catch,couple,field,gathering,grass,grassy,gree...",COM_KITE_003SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_003SM.jpg
3,com_kite_004sm,32,evimg2/a1-10/COM_KITE_004SM.jpg,3,Kite Flying Contest,1995-06,http://digitalimages.ust.hk/gallery/p=639,"fence,grass,person,sign,stand,woman",COM_KITE_004SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_004SM.jpg
4,com_kite_005sm,32,evimg2/a1-10/COM_KITE_005SM.jpg,4,Kite Flying Contest,1995-06,http://digitalimages.ust.hk/gallery/p=639,"building,child,cloudy,field,fly,girl,grass,gra...",COM_KITE_005SM,evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg,evimg2/a1-10/thumbs/thumbs_COM_KITE_005SM.jpg

In [46]:
df1.to_csv('./db/data.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)